version: 0.2

phases:
  install:
    commands:
      - yum install -y aws-cli
  build:
    commands:
      - echo "Deploying to EC2"
      - aws s3 sync . s3://project-cicd-pipeline-radhee

artifacts:
  files:
    - '**/*'
